services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafe_db
    volumes:
      - mysql_vol:/var/lib/mysql
    networks:
      - twotier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 60s

  cafe-app:
    build:
      context: .
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: mysql
      DB_NAME: cafe_db
      DB_PORT: 3306
    ports:
      - "5000:5000"
    networks:
      - twotier
    depends_on:
      mysql:
        condition: service_healthy

networks:
  twotier:

volumes:
  mysql_vol:
